baseURL = "https://thehippo.github.io/mmplus/"
languageCode = "de-de"
title = "mmplus"
theme = "hugo-geekdoc"
enableGitInfo = true
publishDir = "../docs"
disableKinds = ['categories', 'tags']

pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

[markup]
#   [markup.goldmark.renderer]
#     # Needed for mermaid shortcode
#     unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
	geekdocLogo = "logo.png"
	geekdocSearch = false
	geekdocSearchShowParent = false
	geekdocBreadcrumb = false
	geekdocAnchor = false
  	geekdocAnchorCopy = false
